version: '3.3'


services:

    api-gateway:
        container_name: kong
        links:
            - 'kong-database:kong-database'
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=kong-database
            - KONG_PG_PASSWORD=kong
            - KONG_CASSANDRA_CONTACT_POINTS=kong-database
            - KONG_PROXY_ACCESS_LOG=/dev/stdout
            - KONG_ADMIN_ACCESS_LOG=/dev/stdout
            - KONG_PROXY_ERROR_LOG=/dev/stderr
            - KONG_ADMIN_ERROR_LOG=/dev/stderr
            - 'KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl'
        ports:
            - '8000:8000'
            - '8443:8443'
            - '8001:8001'
            - '8444:8444'
        image: kong


    message-bus:
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
        image: 'rabbitmq:3-management'
        ports:
            - '5672:5672'

    api-gateway-db:
        container_name: kong-database
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=kong
            - POSTGRES_DB=kong
            - POSTGRES_PASSWORD=kong
        image: 'postgres:9.6'

    customers-db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example

    tickets-db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example

    payments-db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example

    auth-db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

    customers-api:
      image: customers-api
      restart: always
      links:
        - customers-db
      ports:
        - 8080:8080
    
    customers-service:
      image: customers-service
      restart: always
      links:
        - customers-db
      ports:
        - 8080:8080

    tickets-api:
      image: tickets-api
      restart: always
      links:
        - tickets-db
      ports:
        - 8080:8080

    tickets-service:
      image: tickets-service
      restart: always
      links:
        - tickets-db
      ports:
        - 8080:8080

    payments-service:
      image: payments-service
      restart: always
      links:
        - payments-db
      ports:
        - 8080:8080

    email-service:
      image: email-service
      restart: always
      links:
        - payments-db
      ports:
        - 8080:8080

    notifications-service:
      image: notifications-service
      restart: always
      links:
        - payments-db
      ports:
        - 8080:8080

    web-app:
      image: web-app
      restart: always
      links:
        - payments-db
      ports:
        - 8080:8080

    