- hosts: masters
  become: yes
  tasks:
    - name: Get the token for joining the worker nodes
      become: yes
      become_user: kube
      shell: ps aux
      register: kubernetes_join_command
    - name: Copy join command to local file.
      become: no
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/home/fernando/.tmp/kubernetes_join_command" mode=0777
